//남성&여성 의류 목록
export const data = {
    product_man: [
      {
        id: '1',
        name: '터틀넥 Brown',
        image: '/man1.jpg',
        price: '35,000',
        countInStock: 10,
        rating: 4.5,
        numReviews: 10,
        description: 'high quality shirt',
      },
      {
        id: '2',
        name: '베이직 푸퍼 패딩 Black',
        image: '/man2.jpg',
        price: '89,000',
        countInStock: 0,
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        id: '3',
        name: 'YALE HOODLE GRAY',
        image: '/man3.jpg',
        price: '29,900',
        countInStock: 15,
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        id: '4',
        name: 'Fallet 티셔츠 White ',
        image: '/man4.jpg',
        price: '17,800',
        countInStock: 5,
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        id: '5',
        name: '라운드 니트 Light Green',
        image: '/man5.jpg',
        price: '35,000',
        countInStock: 15,
        rating: 4.5,
        numReviews: 14,
        description: '멋쟁이 신사들을 위한 셔츠',
      },
      {
        id: '6',
        name: '와이드 연청 데님 팬츠 ',
        image: '/man6.jpg',
        price: '35,900',
        countInStock: 13,
        rating: 4.1,
        numReviews: 12,
        description: 'high quality product',
      },
      {
        id: '7',
        name: '캐시미어 블렌드 발마칸 코트 Black ',
        image: '/man7.jpg',
        price: '289,900',
        countInStock: 15,
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        id: '8',
        name: 'ZIP-UP KNIT NAVY ',
        image: '/man8.jpg',
        price: '56,800',
        countInStock: 5,
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        id: '9',
        name: '화이트라벨 노벨티 눕시 다운 자켓',
        image: '/man9.jpg',
        price: '359,900',
        countInStock: 10,
        rating: 4.5,
        numReviews: 10,
        description: 'high quality shirt',
      },
      {
        id: '10',
        name: ' T-Logo Hoodie Black ',
        image: '/man10.jpg',
        price: '59,850',
        countInStock: 0,
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        id: '11',
        name: ' 버핑레더 오버핏 블루종 Suede Brown',
        image: '/man11.jpg',
        price: '57,700',
        countInStock: 15,
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        id: '12',
        name: '삼바 Decon IF0642',
        image: '/man12.jpg',
        price: '179,000',
        countInStock: 5,
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        id: '13',
        name: ' 트랙 덕다운 베스트 GLOSSY BLACK',
        image: '/man13.jpg',
        price: '118,900',
        countInStock: 15,
        rating: 4.5,
        numReviews: 14,
        description: '멋쟁이 신사들을 위한 셔츠',
      },
      {
        id: '14',
        name: '아플리케 트윌 볼 캡 NAVY',
        image: '/man14.jpg',
        price: '78,450',
        countInStock: 13,
        rating: 4.1,
        numReviews: 12,
        description: 'high quality product',
      },
      {
        id: '15',
        name: '오버사이즈 더플 코트 (다크네이비멜란지)',
        image: '/man15.jpg',
        price: '318,000',
        countInStock: 15,
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        id: '16',
        name: '프렌치 치노 투턱 팬츠 (카키 브라운)',
        image: '/man16.jpg',
        price: '47,900',
        countInStock: 5,
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        id: '17',
        name: '코듀로이 셔츠 Pink',
        image: '/man17.jpg',
        price: '47,500',
        countInStock: 15,
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        id: '18',
        name: '빅 트위치 루즈핏 맨투맨 NAVY',
        image: '/man18.jpg',
        price: '28,800',
        countInStock: 5,
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
    ],


    //여성 의류

    product_woman: [
        {
          id: '1',
          name: '어그슬리퍼',
          image: '/woman1.jpg',
          price: '73,400',
          countInStock: 10,
          rating: 4.5,
          numReviews: 10,
          description: 'high quality shirt',
        },
        {
          id: '2',
          name: '플리스자켓 Ivory',
          image: '/woman2.jpg',
          price: '39,900',
          countInStock: 0,
          rating: 4.0,
          numReviews: 10,
          description: 'high quality product',
        },
        {
          id: '3',
          name: '글로시 크롭 푸퍼 자켓 실버',
          image: '/woman3.jpg',
          price: '55,500',
          countInStock: 15,
          rating: 4.5,
          numReviews: 14,
          description: 'high quality product',
        },
        {
          id: '4',
          name: '비건 스웨이이드 집업 자켓 브라운',
          image: '/woman4.jpg', 
          price: '34,900', 
          countInStock: 5,
          rating: 4.5,
          numReviews: 10,
          description: 'high quality product',
        },
        {
          id: '5',
          name: ' Velour Soccer Jersey Black',
          image: '/woman5.jpg',
          price: '65,200',
          countInStock: 15,
          rating: 4.5,
          numReviews: 14,
          description: '멋쟁이 신사들을 위한 셔츠',
        },
        {
          id: '6',
          name: ' THUNDER 브러쉬드 니트  핑크',
          image: '/woman6.jpg',
          price: '36,800',
          countInStock: 13,
          rating: 4.1,
          numReviews: 12,
          description: 'high quality product',
        },
        {
          id: '7',
          name: '니트탑 Black',
          image: '/woman7.jpg',
          price: '24,600',
          countInStock: 15,
          rating: 4.5,
          numReviews: 14,
          description: 'high quality product',
        },
        {
          id: '8',
          name: '오렌지 셔츠',
          image: '/woman8.jpg',
          price: '65',
          countInStock: 5,
          rating: 4.5,
          numReviews: 10,
          description: 'high quality product',
        },
        {
          id: '9',
          name: 'Pink Polo Shirt',
          image: '/woman9.jpg',
          price: '120',
          countInStock: 10,
          rating: 4.5,
          numReviews: 10,
          description: 'high quality shirt',
        },
        {
          id: '10',
          name: 'Marl Polo Shirt',
          image: '/woman10.jpg',
          price: '250',
          countInStock: 0,
          rating: 4.0,
          numReviews: 10,
          description: 'high quality product',
        },
        {
          id: '11',
          name: 'Slim Fit Polo Shirt',
          image: '/woman11.jpg',
          price: '25',
          countInStock: 15,
          rating: 4.5,
          numReviews: 14,
          description: 'high quality product',
        },
        {
          id: '12',
          name: 'Orange Polo Shirt',
          image: '/woman12.jpg', 
          price: '65', 
          countInStock: 5,
          rating: 4.5,
          numReviews: 10,
          description: 'high quality product',
        },
        {
          id: '13',
          name: '핑크 폴로 셔츠',
          image: '/woman13.jpg',
          price: '110',
          countInStock: 15,
          rating: 4.5,
          numReviews: 14,
          description: '멋쟁이 신사들을 위한 셔츠',
        },
        {
          id: '14',
          name: '하늘색 폴로 셔츠',
          image: '/woman14.jpg',
          price: '250',
          countInStock: 13,
          rating: 4.1,
          numReviews: 12,
          description: 'high quality product',
        },
        {
          id: '15',
          name: '슬림핏 셔츠',
          image: '/woman15.jpg',
          price: '25',
          countInStock: 15,
          rating: 4.5,
          numReviews: 14,
          description: 'high quality product',
        },
        {
          id: '16',
          name: '오렌지 셔츠',
          image: '/woman16.jpg',
          price: '65',
          countInStock: 5,
          rating: 4.5,
          numReviews: 10,
          description: 'high quality product',
        },
        {
          id: '17',
          name: '슬림핏 셔츠',
          image: '/woman17.jpg',
          price: '25',
          countInStock: 15,
          rating: 4.5,
          numReviews: 14,
          description: 'high quality product',
        },
        {
          id: '18',
          name: '오렌지 셔츠',
          image: '/woman18.jpg',
          price: '65',
          countInStock: 5,
          rating: 4.5,
          numReviews: 10,
          description: 'high quality product',
        },
      ],
  }